/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Generates depth-aware field controller helpers for reactive forms */
export declare function FieldController(): void
export interface TransformResult {
  code: string
  map?: string
  types?: string
  metadata?: string
}

/** Transform TypeScript code to JavaScript with macro expansion */
export declare function transformSync(code: string, filepath: string): TransformResult
