/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Get the names of all macros in this package */
export declare function __tsMacrosGetMacroNames(): Array<string>

/** Get the manifest of all macros available in this package */
export declare function __tsMacrosGetManifest(): MacroManifest

/** Check if this package exports macros */
export declare function __tsMacrosIsMacroPackage(): boolean

/** Decorator metadata for TypeScript type stubs */
export interface DecoratorManifestEntry {
  module: string
  export: string
  kind: string
  docs: string
}

/** Generates depth-aware field controller helpers for reactive forms */
export declare function fieldController(...features: Array<string | ((...args:
any[]) => unknown)>): void

export declare function FieldController(): void

export declare function JSON(): void

/** Complete manifest for this macro package */
export interface MacroManifest {
  version: number
  macros: Array<MacroManifestEntry>
  decorators: Array<DecoratorManifestEntry>
}

/** Entry for a single macro in the manifest */
export interface MacroManifestEntry {
  name: string
  kind: string
  description: string
  package: string
}

/** Generates depth-aware field controller helpers for reactive forms */
export declare function textAreaController(...features: Array<string | ((...args:
any[]) => unknown)>): void
/** Debug: List all descriptors from inventory */
export declare function __tsMacrosDebugDescriptors(): Array<string>

/** Debug: Get all registered module paths from inventory */
export declare function __tsMacrosDebugGetModules(): Array<string>

/** Debug: Try to look up a macro by module and name */
export declare function __tsMacrosDebugLookup(module: string, name: string): string

/** Get the names of all macros in this package */
export declare function __tsMacrosGetMacroNames(): Array<string>

/**
 * Get the manifest of all macros available in this package
 * This is used by the TypeScript plugin to auto-discover macro packages
 */
export declare function __tsMacrosGetManifest(): MacroManifest

/** Check if this package exports macros (quick probe) */
export declare function __tsMacrosIsMacroPackage(): boolean

/**
 * r" Run this macro with the given context
 * r" Called by the TS plugin to execute macro expansion
 */
export declare function __tsMacrosRunClone(contextJson: string): string

/**
 * r" Run this macro with the given context
 * r" Called by the TS plugin to execute macro expansion
 */
export declare function __tsMacrosRunDebug(contextJson: string): string

/**
 * r" Run this macro with the given context
 * r" Called by the TS plugin to execute macro expansion
 */
export declare function __tsMacrosRunEq(contextJson: string): string

export declare function Clone(...features: Array<string | ClassDecorator | PropertyDecorator | ((...args:
any[]) => unknown) | Record<string, unknown>>): ClassDecorator

/** Generates a toString() method for debugging */
export declare function debug(...features: Array<string | ClassDecorator | PropertyDecorator | ((...args:
any[]) => unknown) | Record<string, unknown>>): PropertyDecorator

export declare function Debug(...features: Array<string | ClassDecorator | PropertyDecorator | ((...args:
any[]) => unknown) | Record<string, unknown>>): ClassDecorator

/** Decorator metadata for TypeScript type stubs */
export interface DecoratorManifestEntry {
  /** Module this decorator is exported from */
  module: string
  /** Export name */
  export: string
  /** Decorator kind ("class", "property", "method", etc.) */
  kind: string
  /** Documentation */
  docs: string
}

export declare function Derive(...features: Array<string | ClassDecorator | PropertyDecorator | ((...args:
any[]) => unknown) | Record<string, unknown>>): ClassDecorator

export declare function Eq(...features: Array<string | ClassDecorator | PropertyDecorator | ((...args:
any[]) => unknown) | Record<string, unknown>>): ClassDecorator

export interface ExpandOptions {
  keepDecorators?: boolean
}

export interface ExpandResult {
  code: string
  types?: string
  metadata?: string
  diagnostics: Array<MacroDiagnostic>
  sourceMapping?: SourceMappingResult
}

/** Expand macros in TypeScript code and return the transformed TS (types) and diagnostics */
export declare function expandSync(code: string, filepath: string, options?: ExpandOptions | undefined | null): ExpandResult

export interface GeneratedRegionResult {
  start: number
  end: number
  sourceMacro: string
}

export interface MacroDiagnostic {
  level: string
  message: string
  start?: number
  end?: number
}

/** Complete manifest for this macro package */
export interface MacroManifest {
  /** Manifest format version */
  version: number
  /** List of macros provided by this package */
  macros: Array<MacroManifestEntry>
  /** List of decorator exports */
  decorators: Array<DecoratorManifestEntry>
}

/** Entry for a single macro in the manifest */
export interface MacroManifestEntry {
  /** The macro name (e.g., "Debug", "JSON") */
  name: string
  /** The macro kind ("derive", "attribute", or "call") */
  kind: string
  /** Description of what the macro does */
  description: string
  /** The Rust package that provides this macro */
  package: string
}

export interface MappingSegmentResult {
  originalStart: number
  originalEnd: number
  expandedStart: number
  expandedEnd: number
}

export interface SourceMappingResult {
  segments: Array<MappingSegmentResult>
  generatedRegions: Array<GeneratedRegionResult>
}

export interface TransformResult {
  code: string
  map?: string
  types?: string
  metadata?: string
}

/** Transform TypeScript code to JavaScript with macro expansion */
export declare function transformSync(code: string, filepath: string): TransformResult
