/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Generates depth-aware field controller helpers for reactive forms */
export declare function FieldController(): void
export interface ExpandResult {
  code: string
  types?: string
  metadata?: string
  diagnostics: Array<MacroDiagnostic>
}

/** Expand macros in TypeScript code and return the transformed TS (types) and diagnostics */
export declare function expandSync(code: string, filepath: string): ExpandResult

export interface MacroDiagnostic {
  level: string
  message: string
  start?: number
  end?: number
}

export interface TransformResult {
  code: string
  map?: string
  types?: string
  metadata?: string
}

/** Transform TypeScript code to JavaScript with macro expansion */
export declare function transformSync(code: string, filepath: string): TransformResult
